// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/6701ebd2b6ff52cae4adcb9b
###
GET http://localhost:3000/contacts/6701eca6b6ff52cae4adcb9c
###
GET http://localhost:3000/contacts/6701ece0b6ff52cae4adcb9d

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4